# Proxy configuration
proxy:
  host: your.proxy.host
  port: 8080
  username: proxy-username
  password: proxy-password
  non-proxy-hosts: localhost|127.0.0.1

# SSL configuration
ssl:
  trust-store: classpath:test.jks
  trust-store-password: changeit

logging:
  level:
    org.apache.hc.client5.http: DEBUG
    org.apache.hc.core5.http: DEBUG